sudo: false
language: haskell
ghc:
  - 7.8
  - 8.0
  - 8.2
install:
  - cabal install packdeps
  - cabal sandbox init
  - cabal install --enable-tests --only-dependencies
script:
  - packdeps utc.cabal
  - cabal configure --enable-tests
  - cabal build
  - cabal test
